FROM docker.io/library/node:18.19

WORKDIR /app

# 使用淘宝镜像源安装依赖
RUN npm config set registry https://registry.npmmirror.com/

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"] 